server:
  port: 8001
spring:
  application:
    name: eureka-client-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

provider:
  ribbon:
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 0
    ConnectTimeout: 250
    ReadTimeout: 500
    OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
##访问actuator 不用安全方式
management:
  security:
    enabled: false
